version: '3'

services:
  react:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app
